version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
      - new_admin_panel_sprint_3_elasticsearch-data:/usr/share/elasticsearch/data
    logging:
      driver: none
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node


  redis-cache_test:
    image: redis:6.2-alpine
    container_name: test_redis
    restart: unless-stopped


  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: test_es
    logging:
      driver: none
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node



  web_test:
    build: ./fastapi-solution
    depends_on:
      - elasticsearch_test
      - redis-cache_test
    logging:
      driver: none
    env_file:
      - ./.env
    environment:
      ES_HOST: elasticsearch_test
      REDIS_HOST: redis-cache_test

  api_tests:
    build: ./tests
    entrypoint: >
      sh -c "python3 /functional/utils/wait_for_es.py
      && python3 /functional/utils/wait_for_redis.py
      && pytest /functional/src/ -s --setup-show -p no:warnings"
    depends_on:
      - elasticsearch
      - elasticsearch_test
      - redis-cache_test
      - web_test
    env_file:
      - ./.env

volumes:
  new_admin_panel_sprint_3_elasticsearch-data:
    external: true
