version: "3.9"

services:
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - cache:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
      - new_admin_panel_sprint_3_elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  web:
    build: ./fastapi-solution
    expose:
      - 8000
    depends_on:
      - elasticsearch
      - redis-cache
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

  redis-cache_test:
    image: redis:6.2-alpine
    container_name: test_redis
    restart: unless-stopped
    volumes:
      - cache:/data

  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: test_es
    volumes:
      - elasticsearch_test_data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  web_test:
    build: ./fastapi-solution
    depends_on:
      - elasticsearch_test
      - redis-cache_test
    env_file:
      - ./.env
    environment:
      ES_HOST: "elasticsearch_test"
      REDIS_HOST: "redis-cache_test"

  api_tests:
    build: ./tests
    entrypoint: >
      sh -c "python3 /functional/utils/wait_for_es.py
      && python3 /functional/utils/wait_for_redis.py
      && pytest /functional/src/ -s --setup-show -p no:warnings"
    depends_on:
      - elasticsearch_test
      - redis-cache_test
      - web_test
    env_file:
      - ./.env

volumes:
  cache_test:
  elasticsearch_test_data:
  cache:
  new_admin_panel_sprint_3_elasticsearch-data:
